name: IRCv3 Working Group
markdown: kramdown
highlighter: rouge
url: https://deploy-preview-355--ircv3.netlify.app/
repository: ircv3/ircv3.github.io
kramdown:
  input: GFM
  auto_ids: false
include:
  - _redirects
exclude:
  - README.md
  - vendor
  - Gemfile*
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
    sass_dir: css
sitemap:
  file: "/sitemap.xml"
collections:
  irc:
    output: true
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: true
